In [6]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set(style="whitegrid", color_codes=True)
import cv2

In [7]:
import pykitti

basedir = 'D:\Thesis\Kitti\Raw'
date = '2011_09_26'
drive = '0009'

# The 'frames' argument is optional - default: None, which loads the whole dataset.
# Calibration, timestamps, and IMU data are read automatically. 
# Camera and velodyne data are available via properties that create generators
# when accessed, or through getter methods that provide random access.
data = pykitti.raw(basedir, date, drive, frames=range(0, 50, 5))

# dataset.calib:         Calibration data are accessible as a named tuple
# dataset.timestamps:    Timestamps are parsed into a list of datetime objects
# dataset.oxts:          List of OXTS packets and 6-dof poses as named tuples
# dataset.camN:          Returns a generator that loads individual images from camera N
# dataset.get_camN(idx): Returns the image from camera N at idx  
# dataset.gray:          Returns a generator that loads monochrome stereo pairs (cam0, cam1)
# dataset.get_gray(idx): Returns the monochrome stereo pair at idx  
# dataset.rgb:           Returns a generator that loads RGB stereo pairs (cam2, cam3)
# dataset.get_rgb(idx):  Returns the RGB stereo pair at idx  
# dataset.velo:          Returns a generator that loads velodyne scans as [x,y,z,reflectance]
# dataset.get_velo(idx): Returns the velodyne scan at idx  

point_velo = np.array([0,0,0,1])
point_cam0 = data.calib.T_cam0_velo.dot(point_velo)

point_imu = np.array([0,0,0,1])
point_w = [o.T_w_imu.dot(point_imu) for o in data.oxts]


In [8]:
coord_factory = iter(data.oxts)

In [9]:
first = next(coord_factory)

In [10]:
first.T_w_imu

array([[ 0.96384258,  0.26588191, -0.017728  ,  0.        ],
       [-0.26646768,  0.96129963, -0.06998565,  0.        ],
       [-0.001566  ,  0.07217909,  0.99739046,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [11]:
second = next(coord_factory)

In [12]:
second.T_w_imu

array([[  9.64011525e-01,   2.65699654e-01,  -9.24521148e-03,
          5.35224373e+00],
       [ -2.65691671e-01,   9.61577913e-01,  -6.91075401e-02,
         -1.52069183e+00],
       [ -9.47185836e-03,   6.90768408e-02,   9.97566376e-01,
          1.13677978e-03],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00]])

In [13]:
second.packet.lat

49.00933409999

In [14]:
point_w[1]

array([  5.35224373e+00,  -1.52069183e+00,   1.13677978e-03,
         1.00000000e+00])

In [15]:
np.set_printoptions(precision=2)

In [16]:
print("{:f} {:f} {:f}".format(point_w[1][0],point_w[1][1],point_w[1][2]))

5.352244 -1.520692 0.001137


In [17]:
len(point_w[:0])

0

In [19]:
first.packet.yaw

-0.2697266732051